### ISSUE TITLE
Unable to create new user account via client

### ISSUE THREAD

**Issue by dchan3** [daveyshindig/radiOMG#10]
I'm opening this issue primarily with regards to implementing the user ban system, but I feel that this is a critical issue that definitely needs to be addressed as soon as possible.

To elaborate, whenever I attempt to create a new user via the client side, I get the error depicted in the following screenshot on the server side:

<img width="572" alt="screen shot 2017-02-09 at 2 11 31 pm" src="https://cloud.githubusercontent.com/assets/11368560/22808768/c1c7c832-eed1-11e6-9775-d6d793a66b6a.png">

**Comment by daveynight** [comment]
Is this still an issue?

**Comment by dchan3** [comment]
Yes. I just tried to make an account on the client-side, and I get the same error as the one depicted in the screenshot.

**Comment by dchan3** [comment]
Check this out. It could be of use since we're using Simple Schema. We may have made a field required by the UsersSchema but not passed upon signup. https://github.com/meteor/meteor/issues/8510

**Comment by dchan3** [comment]
It seems like `Accounts.onCreateUser()` would be helpful: https://docs.meteor.com/api/accounts-multi.html#AccountsServer-onCreateUser

**Comment by daveynight** [comment]
OK. Well that's looking like good stuff to go on, thanks. I won't have time to look into this until possibly tomorrow, if you don't get to it first.

**Comment by daveynight** [comment]
So, it turned out to be an issue with Gmail credentials. User account creation triggers a confirmation email to be sent, and that was failing because the settings file had an incorrect password. SimpleSchema obscured the error, though, for whatever reason. Removing the Users schema revealed a more useful stack trace that helped me resolve this.
